#! /usr/bin/env python3

# Warvis v0.1.0-dev
# (C) 2017 Jérémie Roquet <jroquet@arkanosis.net>
# Released under the ISC license
# https://github.com/Arkanosis/Warvis/

__version__ = '0.1.0-dev'

import os
import sys

def print_usage(file):
    print('Usage: {} <question>'.format(sys.argv[0].split(os.sep)[-1]), file=file)

def warvis(question):
    print(question)

if __name__ == '__main__':

    if len(sys.argv) < 2:
        print_usage(sys.stderr)
        sys.exit(1)

    if sys.argv[1] in ['-h', '--help']:
        print_usage(sys.stdout)
    elif sys.argv[1] == '--version':
        print(__version__)
    else:
        warvis(' '.join(sys.argv[1:]))
